name: GOG Giveaway Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  check-giveaway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run GOG checker
        run: python gog.py
